site_name: "Connected Services TechDocs"
site_description: "The TechDocs for Connected Services."
docs_dir: "docs"
repo_url: "https://github.com/bcgov/csit-connected-services-techdocs"
edit_uri: edit/main/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    # This plugin was included by the DevHub Wizard that created the repo but it is
    # not included in the Docker image used by DevHub's TechDocs plugin
    # - git-revision-date-localized
markdown_extensions:
    - md_in_html
