apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secure-data-exchange-techdocs
  title: Secure Data Exchange Documentation
  description: Documentation for Secure Data Exchange (SDX). Coming soon.
  annotations:
    github.com/project-slug: bcgov/connected-services-techdocs
    backstage.io/techdocs-ref: dir:.
    bcgovpubcode.gov.bc.ca/ministry: CITZ
    bcgovpubcode.gov.bc.ca/product_description: Documentation for Secure Data Exchange (SDX). Coming soon.
    bcgovpubcode.gov.bc.ca/product_owner: Stainton, Drew
    bcgovpubcode.gov.bc.ca/hosting_platform: Not-Applicable
    backstage.io/source-template: template:default/docs-template
  tags:
    - connected-services
    - secure-data-exchange
spec:
  type: documentation
  lifecycle: experimental
  owner: group:default/databc-aps
